--liquibase formatted sql
--changeset enterprise:V004 labels:init

CREATE TABLE LEDGER_ENTRIES (
    ENTRY_ID        VARCHAR(36)    NOT NULL,
    WALLET_ID       VARCHAR(36)    NOT NULL,
    TRANSACTION_ID  VARCHAR(36)    NOT NULL,
    ENTRY_TYPE      VARCHAR(10)    NOT NULL,
    AMOUNT          NUMERIC(19,4)  NOT NULL,
    CURRENCY        VARCHAR(10)    NOT NULL,
    BALANCE_BEFORE  NUMERIC(19,4)  NOT NULL,
    BALANCE_AFTER   NUMERIC(19,4)  NOT NULL,
    DESCRIPTION     VARCHAR(500),
    CREATED_AT      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_LEDGER_ENTRIES PRIMARY KEY (ENTRY_ID),
    CONSTRAINT CHK_LEDGER_TYPE CHECK (ENTRY_TYPE IN ('DEBIT', 'CREDIT')),
    CONSTRAINT CHK_LEDGER_AMOUNT CHECK (AMOUNT > 0)
);

COMMENT ON TABLE LEDGER_ENTRIES IS 'Immutable double-entry bookkeeping ledger — append only';
