--liquibase formatted sql
--changeset enterprise:V005 labels:init
--validCheckSum: 9:4c6cc37050203bd1a7ecec259de55466

CREATE TABLE REFRESH_TOKENS (
    TOKEN_ID    VARCHAR(36)    NOT NULL,
    USER_ID     VARCHAR(36)    NOT NULL,
    TOKEN       VARCHAR(500)   NOT NULL,
    EXPIRES_AT  TIMESTAMP      NOT NULL,
    IS_REVOKED  SMALLINT       NOT NULL DEFAULT 0,
    CREATED_AT  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_REFRESH_TOKENS PRIMARY KEY (TOKEN_ID),
    CONSTRAINT UQ_RT_TOKEN UNIQUE (TOKEN),
    CONSTRAINT FK_RT_USER FOREIGN KEY (USER_ID) REFERENCES WALLET_USERS(USER_ID)
);
