--liquibase formatted sql
--changeset enterprise:V006 labels:init

-- Wallet indexes (performance/query optimization)
CREATE INDEX IDX_WALLET_USER   ON WALLETS(USER_ID);
CREATE INDEX IDX_WALLET_STATUS ON WALLETS(STATUS);

-- Transaction indexes (composite for wallet history — covers 500+ TPS queries)
CREATE INDEX IDX_TXN_WALLET         ON TRANSACTIONS(WALLET_ID);
CREATE INDEX IDX_TXN_STATUS         ON TRANSACTIONS(STATUS);
CREATE INDEX IDX_TXN_CREATED        ON TRANSACTIONS(CREATED_AT);
CREATE INDEX IDX_TXN_WALLET_CREATED ON TRANSACTIONS(WALLET_ID, CREATED_AT);
CREATE INDEX IDX_TXN_REFERENCE      ON TRANSACTIONS(REFERENCE_ID);

-- Ledger indexes
CREATE INDEX IDX_LEDGER_WALLET         ON LEDGER_ENTRIES(WALLET_ID);
CREATE INDEX IDX_LEDGER_TXN            ON LEDGER_ENTRIES(TRANSACTION_ID);
CREATE INDEX IDX_LEDGER_CREATED        ON LEDGER_ENTRIES(CREATED_AT);
CREATE INDEX IDX_LEDGER_WALLET_CREATED ON LEDGER_ENTRIES(WALLET_ID, CREATED_AT);

-- Refresh token user index
CREATE INDEX IDX_RT_USER ON REFRESH_TOKENS(USER_ID);
